// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibjkovfmelmvmphatqyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliamtvdmZtZWxtdm1waGF0cXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzkxMjYsImV4cCI6MjA2ODQxNTEyNn0.fDpw6-JwseCBsBoK8hnzbIX7luSKhlhbONsVi9LazFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});